const API_BASE = "http://localhost:3001";
const state = { token:"", learnerId:"", parentId:"", learnerName:"", mission:null, attempt:null, step:0, responses:{}, completed:[] };
const $ = (selector) => document.querySelector(selector);
async function api(path, options={}) { const response=await fetch(`${API_BASE}${path}`,{...options,headers:{"content-type":"application/json",...(state.token?{authorization:`Bearer ${state.token}`}:{})}}); const body=await response.json(); if(!response.ok) throw new Error(body.error?.message||"Atlas request failed"); return body; }
function show(id){["#login-screen","#workspace-screen","#parent-screen"].forEach(x=>$(x).classList.toggle("hidden",x!==id));}
function esc(value){const node=document.createElement("span");node.textContent=value??"";return node.innerHTML;}
async function loadHome(){const [home,history]=await Promise.all([api(`/learners/${state.learnerId}/home`),api(`/learners/${state.learnerId}/mission-history`)]);state.learnerName=home.learner.name;$("#welcome-heading").textContent=`Welcome, ${home.learner.name}`;$("#mission-count").textContent=`${home.todayMissions.length} missions`;$("#missions-list").innerHTML="";home.todayMissions.forEach(m=>{const card=document.createElement("article"),completed=history.attempts.find(a=>a.missionId===m.id&&a.status==="completed");card.className="mission-card";card.innerHTML=`<div><h3>${esc(m.title)}</h3><p>${esc(m.domains.join(" + "))} · ${m.durationMinutes} min · Status: ${esc(m.status)}</p></div><button type="button">${m.status==="in_progress"?"Resume":completed?"Retry mission":"Start"}</button>`;card.querySelector("button").onclick=()=>completed?retryMission(m.id,completed.id):openMission(m.id);$("#missions-list").append(card);});}
async function retryMission(missionId,attemptId){state.mission=await api(`/missions/${missionId}`);state.attempt=await api(`/attempts/${attemptId}/retry`,{method:"POST",body:"{}"});state.step=0;state.responses={};state.completed=[];$("#mission-heading").textContent=state.mission.title;$("#mission-summary").textContent="Retry started. Your earlier completion remains in history.";$("#workspace-message").textContent="A new retry attempt has started.";$("#progress-area").classList.remove("hidden");renderStep();}
async function openMission(id){state.mission=await api(`/missions/${id}`);state.attempt=await api(`/missions/${id}/attempts/start`,{method:"POST",body:"{}"});state.step=state.attempt.currentStep;state.responses=state.attempt.responses||{};state.completed=state.attempt.completedSteps||[];$("#mission-heading").textContent=state.mission.title;$("#mission-summary").textContent=state.mission.summary;$("#progress-area").classList.remove("hidden");renderStep();}
const confidence=["I need help","I am getting it","I understand","I can explain it"];
function inputFor(step){const value=state.responses[step.type]??(step.type==="number"?"":"");if(step.type==="number")return `<label>Your number<input data-response="answer" type="number" min="0" max="100" value="${esc(state.responses.answer??"")}" inputmode="numeric"><small>Enter a whole number from 0 to 100.</small></label>`;if(step.type==="confidence")return `<fieldset><legend>How confident do you feel?</legend>${confidence.map(c=>`<label class="choice"><input type="radio" name="confidence" value="${c}" ${state.responses.confidence===c?"checked":""}>${c}</label>`).join("")}</fieldset>`;if(["short_text","reflection"].includes(step.type))return `<label>${step.type==="reflection"?"Reflection":"Your response"}<textarea data-response="${step.type}" rows="${state.learnerId.includes("leago")?5:2}" maxlength="1000">${esc(value)}</textarea></label>${state.learnerId.includes("leago")?'<label>Optional research note<textarea data-response="researchNote" rows="2" maxlength="1000">'+esc(state.responses.researchNote||"")+'</textarea></label>':""}`;if(step.type==="choice")return `<div class="choice-grid"><button type="button" data-choice="I practised this">I practised this</button><button type="button" data-choice="I need another look">I need another look</button></div>`;return `<p class="instruction-note">Read this step, then choose Next when you are ready.</p>`;}
function collect(){document.querySelectorAll("[data-response]").forEach(i=>{if(i.value!=='')state.responses[i.dataset.response]=i.type==="number"?Number(i.value):i.value;});const selected=document.querySelector('input[name="confidence"]:checked');if(selected)state.responses.confidence=selected.value;}
function renderStep(){const step=state.mission.steps[state.step], total=state.mission.steps.length, percent=Math.round(state.completed.length/total*100);$("#step-indicator").textContent=`Step ${state.step+1} of ${total}${state.completed.includes(state.step)?" · completed":" · current"}`;$("#mission-progress").value=percent;$("#mission-progress").textContent=`${percent}%`;$("#progress-label").textContent=`${percent}% complete`;$("#current-step").innerHTML=`<h3>${esc(step.title)}</h3><p>${esc(step.instruction)}</p>${inputFor(step)}`;$("#previous-step").disabled=state.step===0;$("#next-step").classList.toggle("hidden",state.step===total-1);$("#complete-mission").classList.toggle("hidden",state.step!==total-1);$("#current-step").querySelectorAll("[data-choice]").forEach(b=>b.onclick=()=>{state.responses.choice=b.dataset.choice;b.setAttribute("aria-pressed","true");});$("#current-step").focus();}
async function save(){collect();state.attempt=await api(`/attempts/${state.attempt.id}`,{method:"PATCH",body:JSON.stringify({currentStep:state.step,completedSteps:state.completed,responses:state.responses})});}
$("#previous-step").onclick=async()=>{collect();state.step--;await save();renderStep();};$("#next-step").onclick=async()=>{collect();if(!state.completed.includes(state.step))state.completed.push(state.step);state.step++;await save();renderStep();};$("#save-exit").onclick=async()=>{await save();$("#progress-area").classList.add("hidden");$("#mission-summary").textContent="Progress saved. Choose Resume when you are ready.";await loadHome();};
$("#abandon-attempt").onclick=async()=>{if(!window.confirm("Abandon this attempt? Your saved attempt will close and cannot be changed."))return;await api(`/attempts/${state.attempt.id}/abandon`,{method:"POST",body:"{}"});$("#progress-area").classList.add("hidden");$("#workspace-message").textContent="Attempt abandoned. You may start this mission again.";await loadHome();};
$("#complete-mission").onclick=async()=>{collect();if(!state.completed.includes(state.step))state.completed.push(state.step);const explanation=state.responses.short_text||state.responses.answer?.toString()||"I completed each guided step.";const reflection=state.responses.reflection||state.responses.confidence||"I am getting it";await api(`/attempts/${state.attempt.id}/complete`,{method:"POST",body:JSON.stringify({currentStep:state.step,completedSteps:state.completed,responses:state.responses,explanation,reflection})});$("#current-step").innerHTML="<h3>Mission complete!</h3><p>Your work and reflection have been saved. Well done.</p>";$("#complete-mission").disabled=true;await loadHome();};
async function loadParent(){const summary=await api(`/parents/${state.parentId}/summary`);$("#parent-summary").innerHTML=summary.children.map(c=>`<article class="panel"><h2>${esc(c.name)}</h2><p><strong>In progress:</strong> ${esc(c.currentMission?.title||"None")} (${c.currentMission?.percentage||0}%)</p><p><strong>Most recently completed:</strong> ${esc(c.mostRecentCompletedMission||"None yet")}</p><p><strong>Confidence:</strong> ${esc(c.confidenceReflection||"Not shared yet")}</p><p><strong>Next focus:</strong> ${esc(c.nextFocus)}</p><p><strong>Family mission:</strong> ${esc(c.familyMission)}</p></article>`).join("");}
$("#login-form").onsubmit=async e=>{e.preventDefault();$("#login-error").textContent="";try{const form=new FormData(e.currentTarget), result=await api("/auth/login",{method:"POST",body:JSON.stringify({username:form.get("username"),password:form.get("password")})});state.token=result.token;if(result.user.role==="parent"){state.parentId=result.user.id;show("#parent-screen");await loadParent();}else{state.learnerId=result.user.id;state.parentId=result.user.parentId;show("#workspace-screen");await loadHome();}}catch(error){$("#login-error").textContent=error.message;}};
$("#companion-form").onsubmit=async e=>{e.preventDefault();const input=$("#companion-input"),message=input.value.trim();if(!message)return;input.value="";const result=await api("/companion/message",{method:"POST",body:JSON.stringify({learnerId:state.learnerId,missionId:state.mission?.id,message})});$("#companion-thread").textContent=result.reply;};
